/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tall.inc;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arvid
 */
public class FardigstallBestallning extends javax.swing.JFrame {

    /**
     * Creates new form FardigstallBestallning
     */
    public FardigstallBestallning() {
        initComponents();

        fillOrderCmb();
    }

    public void fillOrderCmb() {
        String orderIdQuery = "SELECT DISTINCT bestID FROM orderrad";
        ArrayList<String> bestIDLista = SqlFragor.getEnKolumn(orderIdQuery);
        for (String bestID : bestIDLista) {
            String besKlarQuery = "SELECT hattID FROM orderrad where BestID = '" + bestID + "' AND Hattstatus IS NULL";
            ArrayList<String> listaMedOklaraHattar = SqlFragor.getEnKolumn(besKlarQuery);
            if (listaMedOklaraHattar.isEmpty()) {
                bestCmb.addItem(bestID);
            }

        }
    }

    private void fillBesTable() {
        String bestId = String.valueOf(bestCmb.getSelectedItem());

        String klaraHattarQuery = "SELECT hattID FROM orderrad where BestID = '" + bestId + "' AND Hattstatus = 'Klar'";
        ArrayList<String> listaMedKlaraHattar = SqlFragor.getEnKolumn(klaraHattarQuery);
        int antalHattar = listaMedKlaraHattar.size();

        String prisQuery = "SELECT Pris FROM hatt inner join orderrad o on Hatt.HattID = o.HattID where BestID = '" + bestId + "'";
        ArrayList<String> prisLista = SqlFragor.getEnKolumn(prisQuery);
        int totalaPriset = 0;
        for (String pris : prisLista) {
            int intPris = Integer.parseInt(pris);
            totalaPriset = totalaPriset + intPris;

        }

        String kundInfoQuery = "SELECT Fornamn,  Efternamn FROM kund\n"
                + "    Inner join bestallning b on Kund.KundID = b.KundID\n"
                + "WHERE BestID = 1;";

        HashMap<String, String> kundInfo = SqlFragor.getEnRad(kundInfoQuery);

        int i = 0;
        for (String f : kundInfo.values()) {
            besTable.setValueAt(f, NORMAL, i);

            i++;

        }
        besTable.setValueAt(antalHattar, NORMAL, i);
        i++;

        besTable.setValueAt(totalaPriset, NORMAL, i);

    }
    private void angeVikt(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        besTable = new javax.swing.JTable();
        bestCmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        besTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Efternamn", "Förnamn", "Antal Hattar", "Pris", "Vikt"
            }
        ));
        besTable.setRowHeight(40);
        besTable.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(besTable);

        bestCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj Ordernummer" }));
        bestCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestCmbActionPerformed(evt);
            }
        });

        jLabel1.setText("Ange Vikt:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(bestCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bestCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bestCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestCmbActionPerformed
        // TODO add your handling code here:
        fillBesTable();
    }//GEN-LAST:event_bestCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FardigstallBestallning.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FardigstallBestallning.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FardigstallBestallning.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FardigstallBestallning.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FardigstallBestallning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable besTable;
    private javax.swing.JComboBox<String> bestCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
