/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tall.inc;

import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author nsags
 */
public class Kundfrekvens extends javax.swing.JFrame {

    /**
     * Creates new form Kundfrekvens
     */
    public Kundfrekvens() {
        initComponents();
        fyllUppgifter();
    }

    public void fyllUppgifter() {

        ArrayList<HashMap<String, String>> allaStangda;
        String fraga = "SELECT Fornamn, Efternamn, Adress, Tel , COUNT(b.KundID) AS Antal, hattar FROM kund\n"
                + "JOIN bestallning b on kund.KundID = b.KundID\n"
                + "JOIN (\n"
                + "    SELECT count(Fornamn) AS hattar, b.KundID  FROM kund\n"
                + "    JOIN bestallning b on kund.KundID = b.KundID\n"
                + "    JOIN orderrad o on b.BestID = o.BestID\n"
                + "    GROUP BY b.KundID) t2\n"
                + "ON b.KundID = t2.KundID\n"
                + "GROUP BY b.KundID\n"
                + "ORDER BY COUNT(b.KundID) DESC;";

        allaStangda = SqlFragor.getFleraRader(fraga);

        String rubrik = "Förnamn:"
                + "\t" + "Efternamn"
                + "\t" + "Adress:"
                + "\t" + "Telefon:"
                + "\t" + "Beställningar:"
                + "\t" + "Hattar:" + "\n";

        txtKunder.append(rubrik);

        for (HashMap<String, String> info : allaStangda) {
            txtKunder.append(info.get("Fornamn")
                    + "\t" + info.get("Efternamn")
                    + "\t" + info.get("Adress")
                    + "\t" + info.get("Tel")
                    + "\t" + info.get("Antal")
                    + "\t" + info.get("hattar") + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtKunder = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtKunder.setEditable(false);
        txtKunder.setColumns(20);
        txtKunder.setRows(5);
        jScrollPane1.setViewportView(txtKunder);

        jLabel1.setText("Antal beställningar per kund");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new Startsida().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtKunder;
    // End of variables declaration//GEN-END:variables
}
