/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tall.inc;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noahjarvback
 */
public class SeListaMaterial extends javax.swing.JFrame {

    /**
     * Creates new form SeListaMaterial
     */
    public SeListaMaterial() {
        initComponents();
        fyllLista();
    }
    
    private void fyllLista() {
        String query = "select Beskrivning, Tyg, Farg from Hatt\n"
                + "join Farg on Farg.FargID = Hatt.FargID\n"
                + "join Tyg on Tyg.TygID = Hatt.TygID\n"
                + "join Orderrad on Orderrad.HattID = Hatt.HattID\n"
                + "join Bestallning on Bestallning.BestID = Orderrad.BestID\n"
                + "where Status = 'Pågående'\n"
                + "or Status = 'Öppen'";
        ArrayList<HashMap<String, String>> hattLista = SqlFragor.getFleraRader(query);
        System.out.println(hattLista);
        fyllRader(hattLista);
    }

    private void fyllRader(ArrayList<HashMap<String, String>> hattlista) {
        Object[][] orderrad = new Object[hattlista.size()][4];
        int rad = 0;
        for (HashMap<String, String> hatt : hattlista) {
            orderrad[rad][0] = hatt.get("Beskrivning");
            orderrad[rad][1] = hatt.get("Tyg");
            orderrad[rad][2] = hatt.get("Farg");
            rad++;
        }
        listaRader(orderrad);
    }

    /*
    Skriver ut en 2D array i en jList
     */
    private void listaRader(Object[][] orderrad) {
        DefaultTableModel model = (DefaultTableModel) tblLista.getModel();
        model.setNumRows(0);
        for (int i = 0; i < orderrad.length; i++) {
            model.addRow(orderrad[i]);
        }
    }                  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeInfo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSeInfo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblSeInfo.setText("Se information om material för hattar");

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hatt ", "Tyg", "Färg"
            }
        ));
        jScrollPane2.setViewportView(tblLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeInfo)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblSeInfo)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSeInfo;
    private javax.swing.JTable tblLista;
    // End of variables declaration//GEN-END:variables
}
