/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tall.inc;

import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author nsags
 */
public class SeOrderStatus extends javax.swing.JFrame {

    /**
     * Creates new form SeOrderStatus
     */
    public SeOrderStatus() {
        initComponents();
        fyllOrderLista();
        fyllCmbStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrderLista = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtOrderLista.setColumns(20);
        txtOrderLista.setRows(5);
        jScrollPane1.setViewportView(txtOrderLista);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alla" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        jLabel1.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTillbaka))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new Startsida().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        ArrayList<HashMap<String, String>> filter;
        String status = cmbStatus.getSelectedItem().toString();
        String fraga3 = "Select BestID, Status, KundID, TullID, Prio FROM bestallning where Status like '" + status + "'";
        filter = SqlFragor.getFleraRader(fraga3);
        int i = cmbStatus.getSelectedIndex();
        if (filter != null) {
            txtOrderLista.setText("");
            String rubrik2 = " BeställningsID:"
                + "\t" + "Status:"
                + "\t" + "Kund ID"
                + "\t" + "TullID:"
                + "\t" + "Prio:" + "\n";
            txtOrderLista.append(rubrik2);
            
            for(HashMap<String, String> info : filter){
                txtOrderLista.append(info.get("BestID")
                + "\t" + info.get("Status")
                + "\t" + info.get("KundID")
                + "\t" + info.get("TullID")
                + "\t" + info.get("Prio") + "\n");
                
            }
        }
        else if (cmbStatus.equals(i)){
            fyllOrderLista();
        }

    }//GEN-LAST:event_cmbStatusActionPerformed

            
    private void fyllOrderLista() {

        ArrayList<HashMap<String, String>> allInfo;
        String fraga = "SELECT BestID, Status, KundID, TullID, Prio FROM bestallning";

        allInfo = SqlFragor.getFleraRader(fraga);

        String rubrik = " BeställningsID:"
                + "\t" + "Status:"
                + "\t" + "Kund ID"
                + "\t" + "TullID:"
                + "\t" + "Prio:" + "\n";

        txtOrderLista.append(rubrik);

        for (HashMap<String, String> info : allInfo) {
            txtOrderLista.append(info.get("BestID")
                    + "\t" + info.get("Status")
                    + "\t" + info.get("KundID")
                    + "\t" + info.get("TullID")
                    + "\t" + info.get("Prio") + "\n");
        }
    }

    private void fyllCmbStatus() {
        String fraga2 = "SELECT Status FROM bestallning";
        ArrayList<String> status;

        status = SqlFragor.getEnKolumn(fraga2);

        for (String info : status) {
            cmbStatus.addItem(info);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtOrderLista;
    // End of variables declaration//GEN-END:variables
}
